server:
  port: 8097

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:   
    stream:
      bindings:
        foodOrdersChannelInput:          
          destination: foodExchange.food
          group: group1
          contentType: application/json
        customerChannelInput:
          destination: customerExchange.customer
          group: group1
          contentType: application/json